In [16]:
import os
import numpy as np
import  yaml

def load_config_file(config_file_path: str) -> dict:
    """Load a YAML configuration file.

    Args:
        config_file_path (str): The base name of the configuration file.

    Returns:
        dict: The loaded configuration parameters.
    """


    with open(config_file_path, 'r') as config_file:
        config_params = yaml.safe_load(config_file)

    return config_params.get('robot_config', {}).get('ros__parameters', {})

## Tranformation odom to map

In [17]:
# tranformation odom to map
T_mo = np.array(
    [[1, 0, 0, 4],
    [0, 1, 0, 0.2],
    [0, 0, 1, 0],
    [0, 0, 0, 1]]
)
print(T_mo)

[[1.  0.  0.  4. ]
 [0.  1.  0.  0.2]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]


## Tranformation car to odom

In [18]:
# tranformation car to odom
robot_config_path =  "/home/muhammed/Main/programming/ros2_ws/hello_world_ws/src/hello_world_ros2_edx/hrwros_week3/hrwros_gazebo/config/robot_config.yaml"
mobile_robot = load_config_file(robot_config_path)['robot_groups']['mobile_robot']
print(mobile_robot)
x = mobile_robot['x']
y = mobile_robot['y']
z = mobile_robot['z']

{'x': -4.0, 'y': -0.2, 'z': 0.0}


In [19]:
T_oc = np.array(
    [[1, 0, 0, x],
    [0, 1, 0, y],
    [0, 0, 1, z],
    [0, 0, 0, 1]]
)
print(T_oc)

[[ 1.   0.   0.  -4. ]
 [ 0.   1.   0.  -0.2]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]


## Tranformation car to map

In [20]:
# Tranformation car to map
T_cm = T_mo @ T_oc
print(T_cm)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
